language: node_js
node_js:
  - "10"
addons:
  sonarcloud:
    organization: "moser-ss-github"
    token:
        secure: "maLX5L0TGfkRmsXktAQ+J1AMgXsvXyBNKH7kfoXTPyyyqz+nKtUYxeuFeczTHmLbxNa63HcbE3OXsYMhEZV0HcZ50lkkdOH1foyR2AYQFhV3D/Nm8MU5IjGbTIHuJVgNZPu7kZvgf0oq2hjqndpECuPqJdd65q3qwqhhjxwVWnBkYFAG6hOB5L9e6XOZhBzakU9cSWQ7DJh56jhiJcAir8GmleBvmzAh80JQm8J5yG763j+wAOhzIUze56zbyqfHzaNZNLIJYW6BAbpKf/MIzRJPmlbNVKXI0Eqo0/mh9lCBiv6UD+XnyAkkQxVsXUR7vlCJusByYtZnI/s7WOsHWt6NXi8Hrj7UP6XSZd23ykNZc/CXgd4BHhSMNAvZBcNG+xFVubRYguZajyeHjYONC7U8hvZvk2mn7Lb8hTdQb8GN5shv6w+ieNVaC2kxmQoLfsO6VwMDRgZkqBKUSTU9vlVnDpO96si4uzJI+L+Xof15NB2ACSgyUoBaf3ao9C1PsOuVEgh8geKaFZLNZtWbaOLifUf4Y/WMCeJ7fyvbMPvv2O9tyH8rHwfDBTgUe8W+z2YukqR5MCa7+1l0OKbO5X3tAOmuqkYQm711PZIYCBPRDM1ESHQSLySDoP3JcXzDhbei1q1wnnRKd5zlEkaJKJyQ+2Ybg6/C4dzN0isnkLk="
script:
  - npm build
  - npm run test:coverage
  - sonar-scanner
