name: CI-CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
    - run: npm run build:prod
    - run: npm run test:coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}