name: CI-CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    env:
        FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
        FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
        FIREBASE_DATABASE_URL: ${{secrets.FIREBASE_DATABASE_URL}}
        FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
        FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
        FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - run: npm ci
    - run: npm run build:prod
    - run: npm run test:coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}